version: '2'
services:
    shopify-app:
        image: shopify
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://shopify-mysql:3306/shopify?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shopify-mysql:
        extends:
            file: mysql.yml
            service: shopify-mysql
